### ISSUE TITLE
Feature request - avoid supplying AWS credentials

### ISSUE THREAD

**Issue by concurrencylabs** [FittedCloud/ebscostanalyzer#1]
Thanks for building this tool. I have the following feature request:

Avoid requiring users to include their AWS credentials when calling the script. 

I see the following alternatives (they're not mutually exclusive):

1)Asking for an AWS credentials profile instead, similar in the way the AWS_DEFAULT_PROFILE environment variable is set when using Boto or the CLI
2)Set the AWS_DEFAULT_PROFILE environment variable prior to calling the script
3)Add support for running the script from an EC2 instance with an IAM Instance Profile attached to it. 

Advantages of these alternatives:
- It's more secure calling the script this way. This will avoid forcing users to hard-code credentials if they want to automate script execution. In general, avoiding the need to explicitly supply AWS credentials is more desirable from a security standpoint.
- Less parameters and better user experience. Supplying credentials involves: 1)finding my AWS credentials, 2)copying credentials, 3)pasting credentials.

**Comment by G7Nation** [comment]
I've implemented #1 and #2 from your suggestions.  #3 may be added in a future release.

There's a new option, -p or --profile, with which you can enter a profile name instead of using the -a and -s options.  For example:
<pre>
$ python EbsCostAnalyzer.py -p default  # uses the profile named "default"
</pre>
If none of the -p, -a, or -s options are provided, it will use the AWS_DEFAULT_PROFILE environment variable if it exists.  For example:
<pre>
$ export AWS_DEFAULT_PROFILE=default
$ python EbsCostAnalyzer.py  # uses the profile named "default"
</pre>
